local_backend: true
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/assets" # Location where files will be stored in the repo
public_folder: "/assets" # The src attribute for uploaded media

collections:
  - name: pages
    label: "Pages" # Used in the UI
    folder: "src/contents/pages" # The path to the folder where the documents are stored
    format: "frontmatter"
    create: true
    #nested: { depth: 3 }
    #meta: { path: { widget: string, label: 'uri', index_file: 'index' } }
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "datetime", widget: "datetime" }
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        max: 6
        min: 1
        fields:
          - label: "Image"
            name: "image"
            widget: "object"
            fields:
              - { label: "Url", name: "url", widget: "image" }
              - { label: "Alt", name: "alt", widget: string, default: "thumb" }
      - label: "Blocks"
        name: "blocks"
        widget: "list"
        types:
          - label: "Hero Block"
            name: "hero"
            required: false
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string", required: false }
              - { label: "Text", name: "text", widget: "string", required: false }
              - { label: "Image", name: "image", widget: "image",  required: false }
          - label: "Section"
            name: "section"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string", required: false }
              - { label: "Show link", name: "linked", widget: "boolean", default: false }
              - { label: "Anchor Name", name: "link", widget: "string", pattern: ["^[a-z0-9]+(?:-[a-z0-9]+)*$", "Must be a link name, no spaces or special chars"] , required: false}
              - { label: "Content", name: "body", widget: "markdown", required: true }
          - label: "Image Block"
            name: "imageBlock"
            widget: "object"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt text", name: "alt", widget: "string" }
          - label: "News Section"
            name: "news"
            widget: "relation"
            collection: "news"
            multiple: true
            min: 2
            max: 4
            search_fields: ["title"]
            display_fields: ["title"]
            value_field: "{{slug}}"
          - label: "Events Section"
            name: "events"
            widget: "relation"
            collection: "events"
            multiple: true
            min: 2
            max: 4
            search_fields: ["title"]
            display_fields: ["title"]
            value_field: "{{slug}}"
          - label: "Works Section"
            name: "works"
            widget: "relation"
            collection: "works"
            multiple: true
            min: 2
            max: 4
            search_fields: ["title"]
            display_fields: ["title"]
            value_field: "{{slug}}"
  - name: "news"
    label: "News" # Used in the UI
    folder: "src/contents/news" # The path to the folder where the documents are stored
    format: "frontmatter"
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - label: "Image"
        name: "image"
        widget: "object"
        required: false
        fields:
            - { label: "Url", name: "url", widget: "image" }
            - { label: "Alt", name: "alt", widget: string, default: "thumb" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description",  default: "" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["news"], required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "events"
    label: "Events" # Used in the UI
    folder: "src/contents/events" # The path to the folder where the documents are stored
    format: "frontmatter"
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description",  default: "" }
      - { label: "Start Date", name: "from", widget: "datetime", required: false }
      - { label: "End Date", name: "to", widget: "datetime", required: false }
      - { label: "Location", name: "location", widget: "string", required: false }
      - { label: "Url", name: "url", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", default: ["events"], required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "works"
    label: "Artworks" # Used in the UI
    folder: "src/contents/works" # The path to the folder where the documents are stored
    format: "frontmatter"
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - label: "Image"
        name: "image"
        widget: "object"
        required: false
        fields:
            - { label: "Url", name: "url", widget: "image" }
            - { label: "Alt", name: "alt", widget: string, default: "artwork" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description",  default: "" }
      - { label: "Author", name: "author", widget: "string", required: false}
      - { label: "Tags", name: "tags", widget: "list", default: ["artworks"], required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Global config"
    name: globals
    format: "json"
    editor:
      preview: false
    files:
      - label: "Site options"
        name: site
        file: "src/contents/config/data.json"
        fields:
          - { label: "Site name", name: "siteName", widget: "string", required: false}
          - { label: "Domain", name: "domain", widget: "string", required: false}
          - { label: "Logo", name: "logo", widget: "image", required: false}
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Subtitle"
                name: "subtitle"
                widget: "string"
                required: false
              - label: "logo"
                name: "image"
                widget: "image"
                required: false
              - label: "Description"
                name: "description"
                required: false
                widget: "string"
              - label: "keywords"
                name: "keywords"
                widget: "list"
                required: false
                default: ["italia"]
          - label: "Socials"
            name: "socials"
            widget: "list"
            fields:
              - label: "title"
                name: "title"
                widget: "string"
              - label: "url"
                name: "url"
                widget: "string"
          - label: "Header"
            name: "header"
            widget: "list"
            fields:
              - label: "Show Socials"
                name: "socials"
                widget: "boolean"
              - label: "Navigation"
                name: "nav"
                widget: "list"
                fields:
                  - label: "title"
                    name: "title"
                    widget: "string"
                  - label: "link"
                    name: "link"
                    widget: "string"
                  - label: "childs"
                    name: "childs"
                    required: false
                    widget: "list"
                    fields:
                    - label: "title"
                      name: "title"
                      widget: "string"
                    - label: "link"
                      name: "link"
                      widget: "string"
          - label: "Footer"
            name: "footer"
            widget: "list"
            fields:
              - label: "Rows"
                name: "rows"
                widget: "list"
                fields:
                  - label: "id"
                    name: "id"
                    widget: "number"
                  - label: "Sections"
                    name: "sections"
                    required: false
                    widget: "list"
                    fields:
                    - label: "Title"
                      name: "title"
                      widget: "string"
                    - label: "Show socials"
                      name: "socials"
                      widget: "boolean"
                      default: false
                    - label: "Links"
                      name: "links"
                      required: false
                      widget: "list"
                      fields:
                      - label: "title"
                        name: "title"
                        widget: "string"
                      - label: "url"
                        name: "url"
                        widget: "string"
                    - label: "Contatti"
                      name: "texts"
                      required: false
                      widget: "list"




